name: Hello
on:
  push:
    branches:
      - main
      - develop
      - "release/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: |
          echo "IP is ${{ vars.TEST_IP }}"
          echo "my name is ${{ vars.MY_NAME }}"
          echo "my secret is ${{ secrets.DOCKER_PASSWORD }}"
