name: Hello
on:
  push:
    branches:
      - main
      - develop
      - "release/**"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: Build step
        run: echo "A demo build"
