name: Hello
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: Build step
        run: echo "A demo build"
  test:
    runs-on: ubuntu-slim
    steps:
      - name: Test Phase
        run: echo "Running tests"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        run: echo "Deploying app"
